micronaut:
  application:
    name: cdc

datasources:
  default:
    url: jdbc:mysql://${BD_HOST:localhost}:3306/cdcMicronaut?createDatabaseIfNotExist=true
    username: root
    password: ${BD_PASSWORD:06071991}

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
